version: "3"

services:
  challenge-meli:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./components:/home/node/src/components
      - ./mocks:/home/node/src/mocks
      - ./pages:/home/node/src/pages
      - ./public:/home/node/src/public
      - ./styles:/home/node/src/styles
      - ./utils:/home/node/src/utils
